### PR TITLE
Remove several panics in write_image

### LINKED ISSUE #35: Encoding panics if the input is too short
The following code causes a panic in the encoder:

```rust
let input_data = vec![1,2,3].as_slice();
let mut output = Vec::new();
let mut output_stream = Cursor::new(output);
if let Ok(mut tiff) = TiffEncoder::new(&mut output_stream) {
    tiff.write_image::<colortype::RGB8>(50, 50, &input_data)
}
```
Error message:
`thread 'main' panicked at 'index 7500 out of range for slice of length 173', src/libcore/slice/mod.rs:2349:5`

### PR DESCRIPTION
**Pull request by aschampion**
Closes #35. It's not decided this is the preferred behavior, but my opinion is that since `write_image` returns a result rather than `()`, the least surprising behavior is to panic in as few cases as possible. It's ambiguous whether `InvalidData` or `UnexpectedEof` would be more appropriate here.

The buffer length is compared vs `width * height` to avoid a redundant comparison for every strip (because Rust still doesn't have non-panicking range indexing 🙁), but this limits the `width * height` to `u32`, so would have to change if BigTIFF support is planned.

Two other unwraps are converted to trys. These should be uncontroversial.

### CODE REVIEW

File: src/encoder/mod.rs [hunk 1]
```diff
@@ -238,13 +238,18 @@ impl<W: Write + Seek> TiffEncoder<W> {
 
     /// Convenience function to write an entire image from memory.
     pub fn write_image<C: ColorType>(&mut self, width: u32, height: u32, data: &[C::Inner]) -> TiffResult<()> where [C::Inner]: TiffValue {
+        if data.len() < (width * height) as usize {
```
Comment (Shnatsel) [inline src/encoder/mod.rs]: `width * height` could overflow `usize` on 32-bit systems. Please use [`checked_mul()`](https://doc.rust-lang.org/std/primitive.u32.html#method.checked_mul) instead.

Comment (HeroicKatora) [inline src/encoder/mod.rs]: Should be `(width as usize * height as usize)` or a checked mul.

Comment (HeroicKatora) [reply src/encoder/mod.rs]: See @Shnatsel

Comment (HeroicKatora) [reply src/encoder/mod.rs]: And convert `width` and `height` to `usize` before the multiplication.

Comment (aschampion) [reply src/encoder/mod.rs]: If the multiplication overflows (*without* first casting to `usize`), presumably an error should be returned because the image is too big for TIFF anyway (32 bit offsets)?

Comment (HeroicKatora) [reply src/encoder/mod.rs]: Not necessarily. Compression, less then 8 bits per color, ... Just keep it separate, the check is cheap either way.

Comment (aschampion) [reply src/encoder/mod.rs]: Fair enough, I pushed an amend so the check is done now after a `usize` cast.

**Comment by Shnatsel** [comment]
CI test is failing due to #30

**Comment by HeroicKatora** [comment]
> (because Rust still doesn't have non-panicking range indexing slightly_frowning_face),

Yes it does [slice::get](https://doc.rust-lang.org/std/primitive.slice.html#method.get) supports a generic `S: SliceIndex<[T]>` argument, implemented e.g. by `Range<usize>`.

**Comment by aschampion** [comment]
> > (because Rust still doesn't have non-panicking range indexing slightly_frowning_face),
> 
> Yes it does [slice::get](https://doc.rust-lang.org/std/primitive.slice.html#method.get) supports a generic `S: SliceIndex<[T]>` argument, implemented e.g. by `Range<usize>`.

Awesome! I'd been following the RFC but somehow missed it getting stabilized so long ago.

**Comment by HeroicKatora** [comment]
The `SliceIndex` trait itself is not stable to implement but its `impls` can be used in stable. Maybe that was the source of confusion.

**Comment by birktj** [comment]
If this is the behavior we want, we should also fix `ImageEncoder::write_strip` that currently contains an `assert_eq`

**Comment by aschampion** [comment]
Done.

**Comment by aschampion** [comment]
Rebased on master to fix an unrelated failing test. All tests are green now.

**Comment by Shnatsel** [comment]
This has once again diverged with master. Can we get a clear yay or nay on these changes from the maintainers so that this can be merged without any more divergences, or dropped if this direction is not desirable?

**Comment by HeroicKatora** [comment]
Did the rebase right now, and a clear yes. Merging once travis says this is fine as well.
